import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/SmoothScroll";
import Navbar from "./components/Navbar";
import { Playfair_Display, Inter, Cormorant_Upright, Pinyon_Script} from "next/font/google";
import Preloader from "./components/Preloader";
//import { Playfair_Display, Inter, Cormorant_Upright } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const serif = Playfair_Display({ 
  subsets: ["latin"], 
  variable: "--font-serif",
  weight: ["400", "700", "900"] 
});

const sans = Inter({ 
  subsets: ["latin"], 
  variable: "--font-sans" 
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const calligraphy = Pinyon_Script({ 
  subsets: ["latin"], 
  weight: ["400"],
  variable: "--font-calligraphy" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${serif.variable} ${sans.variable} ${calligraphy.variable}`}>
      <body className="font-sans antialiased bg-paper text-charcoal">
        <Preloader /> {/* Add this here */}
        <SmoothScroll>
          <Navbar />
          <main>{children}</main>
        </SmoothScroll>
      </body>
    </html>
  );
}



